
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utuabiuxkgixnzibxekn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dWFiaXV4a2dpeG56aWJ4ZWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTc4NDEsImV4cCI6MjA1OTQzMzg0MX0.U2xQrB_j8JlG1L6ZOGlXGi0LPYn3-FSBNXCq1BLej00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create type-safe helpers for each table
export const Tables = {
  blockchain_transactions: 'blockchain_transactions',
  vulnerability_analyses: 'vulnerability_analyses',
  private_key_fragments: 'private_key_fragments'
};
